export const CHECKIN_CATEGORIES = [
  {
    id: "daily_love_care",
    label: "Daily",
    title: "Daily Love & Care",
    messages: [
      "Good morning, my favorite person.",
      "Did you sleep well last night?",
      "I hope your day starts with a smile.",
      "Don't forget to eat properly today.",
      "I miss you already.",
      "You make my life better just by being in it.",
      "Text me when you reach safely.",
      "I'm proud of you. Always.",
      "I wish I could hug you right now.",
      "You're always on my mind.",
      "Have you had water yet? Stay hydrated!",
      "I hope something amazing happens to you today.",
      "You deserve all the happiness in the world.",
      "I feel lucky to have you.",
      "You're my comfort place.",
      "Thinking of you makes me smile.",
      "Take care of yourself, okay?",
      "I'm here for you, no matter what.",
      "You mean more to me than you know.",
      "Just checking on you.",
      "I love the way you exist.",
      "I hope your day is going smoothly.",
      "You're my favorite notification.",
      "Can't wait to talk to you later.",
      "I believe in you.",
      "You're doing better than you think.",
      "You make everything feel easier.",
      "I hope you're taking breaks too.",
      "You're enough, always.",
      "I appreciate you so much.",
      "You're my peace.",
      "I'm always rooting for you.",
      "You matter to me. A lot.",
      "You make my heart feel full.",
      "I hope you're smiling right now.",
      "You're my safe place.",
      "I care about you deeply.",
      "Don't stress too much, I got you.",
      "I'm thinking about you all day.",
      "You're my favorite part of every day.",
    ],
  },
  {
    id: "cute_romantic",
    label: "Romantic",
    title: "Cute & Romantic",
    messages: [
      "I wish I could steal a kiss right now.",
      "You're too cute, it's unfair.",
      "I fell for you a little more today.",
      "I love you more than yesterday.",
      "You make my heart race.",
      "I miss your voice.",
      "You're my favorite distraction.",
      "I want to be with you forever.",
      "You're the best thing that happened to me.",
      "I crave your presence.",
      "You're my dream come true.",
      "I love your smile so much.",
      "You're my kind of perfect.",
      "I want to hold your hand all the time.",
      "You make love feel easy.",
      "You're stuck in my head in a good way.",
      "I adore you.",
      "I love being yours.",
      "You're my favorite person to annoy.",
      "I'd choose you again and again.",
      "I love the way you laugh.",
      "You're my happiness.",
      "I miss you more than I expected.",
      "You're my person.",
      "I love how you make me feel.",
      "You're everything I wanted.",
      "I can't stop thinking about you.",
      "You complete me.",
      "I love you endlessly.",
      "You're my home.",
      "You're the reason I smile randomly.",
      "I'm obsessed with you.",
      "You're my forever.",
      "I love your vibe.",
      "You're my favorite human.",
      "I feel safe with you.",
      "I love being around you.",
      "You're my heart.",
      "I love us.",
      "You're irreplaceable.",
    ],
  },
  {
    id: "fun_teasing_playful",
    label: "Playful",
    title: "Fun, Teasing & Playful",
    messages: [
      "Stop being so cute, it's distracting.",
      "You owe me a hug.",
      "Why are you always in my thoughts?",
      "I blame you for my smile.",
      "You're officially my problem now.",
      "I think I like you... a lot.",
      "Don't miss me too much.",
      "I'm your favorite, admit it.",
      "You're lucky to have me.",
      "I'm stealing you forever.",
      "I need attention ASAP.",
      "You better text me first next time.",
      "I'm jealous of your pillow.",
      "You're my favorite headache.",
      "Come here, I need a hug.",
      "You're not allowed to ignore me.",
      "I miss annoying you.",
      "You're too addictive.",
      "I need my daily dose of you.",
      "You're mine, okay?",
      "I'll fight anyone for you.",
      "I'm thinking about you... again.",
      "Why are you so perfect?",
      "You make me soft.",
      "You owe me a date.",
      "I want your time.",
      "I'm bored, entertain me.",
      "You're my favorite habit.",
      "You're too hard to ignore.",
      "I miss bullying you lovingly.",
    ],
  },
  {
    id: "apology_emotional",
    label: "Apology",
    title: "Apology & Emotional",
    messages: [
      "I'm sorry if I hurt you.",
      "I didn't mean to upset you.",
      "I'll do better next time.",
      "You deserve better from me.",
      "I hate when we fight.",
      "I care about you too much to lose you.",
      "I'm really sorry, please forgive me.",
      "Let's fix this together.",
      "I understand your feelings.",
      "I miss us being okay.",
      "I'll work on myself.",
      "You mean too much to me.",
      "I don't want distance between us.",
      "I regret hurting you.",
      "Please don't stay upset for long.",
      "I'm here to talk when you're ready.",
      "I'll listen, I promise.",
      "I want to make things right.",
      "You matter more than my ego.",
      "I never want to lose you.",
      "I'm sorry for my mistakes.",
      "I value you deeply.",
      "Let's not give up on us.",
      "I'll be more careful.",
      "I didn't handle it well.",
      "I'm trying to understand you better.",
      "You deserve peace.",
      "I'll respect your feelings.",
      "I'm sorry for everything.",
      "I love you, even in tough moments.",
    ],
  },
  {
    id: "support_motivation",
    label: "Support",
    title: "Support & Motivation",
    messages: [
      "You've got this.",
      "I believe in you completely.",
      "Don't give up now.",
      "You're stronger than you think.",
      "I'm always on your side.",
      "Keep going, you're doing great.",
      "I'm proud of your effort.",
      "You inspire me.",
      "You're capable of amazing things.",
      "Take it one step at a time.",
      "I'm here if you need anything.",
      "You're doing your best, and that's enough.",
      "I admire your strength.",
      "You'll get through this.",
      "Don't doubt yourself.",
      "I trust your decisions.",
      "You're growing every day.",
      "I'm proud to call you mine.",
      "You're not alone.",
      "You'll succeed, I know it.",
      "I'm cheering for you always.",
      "You make me proud.",
      "Keep pushing forward.",
      "You're amazing at what you do.",
      "I see your effort.",
      "You're unstoppable.",
      "I support you fully.",
      "You're doing enough.",
      "Believe in yourself like I do.",
      "You're incredible.",
    ],
  },
  {
    id: "night_missing_you",
    label: "Night",
    title: "Night & Missing You",
    messages: [
      "Good night, sleep well.",
      "Dream about me.",
      "I miss you tonight.",
      "I wish you were here.",
      "Sleep peacefully, my love.",
      "I hope you had a good day.",
      "Can't wait to talk tomorrow.",
      "You're my last thought before sleep.",
      "I'm sending you a virtual hug.",
      "I wish I could say goodnight in person.",
      "Rest well, you deserve it.",
      "I'll be thinking of you.",
      "Sweet dreams.",
      "I miss your presence.",
      "Sleep tight.",
      "You're always in my heart.",
      "I hope tomorrow is better for you.",
      "I love you, good night.",
      "I'm already missing you again.",
      "I wish we were together right now.",
      "I'll see you in my dreams.",
      "I hope you sleep peacefully.",
      "I'm here even when we're apart.",
      "You mean everything to me.",
      "I'm grateful for you tonight.",
      "I wish I could hold you.",
      "Don't stay up too late.",
      "Take care of yourself.",
      "Good night, my favorite person.",
      "I love you, always.",
    ],
  },
];

export const CHECKIN_PRESETS = CHECKIN_CATEGORIES.flatMap((category) =>
  category.messages.map((message, index) => ({
    mood: `${category.id}_${String(index + 1).padStart(3, "0")}`,
    message,
    categoryId: category.id,
    categoryTitle: category.title,
  }))
);

export function getCheckInPreset(mood) {
  return CHECKIN_PRESETS.find((preset) => preset.mood === mood);
}
